---
- name: SET ROUTER BANNERS
  hosts: all
  gather_facts: no

  tasks:


    - name: LOAD BANNER ONTO NETWORK DEVICE
      include_tasks: "{{ ansible_network_os }}_banner.yaml"
      vars:
        - network_banner:  "{{ net_banner | default(None) }}"
#        - banner_type: "{{ banner_type | default('login') }}"
        - banner_type: "login"
      when: ansible_network_os is defined
